### ISSUE TITLE
MtLogTailer.log fills disk with repeated "System.ArgumentException: The output char buffer is too small to contain the decoded characters..."

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#100]
Something caused MTLogTailer.exe running on INX-SRV-APPL79 to repeatedly write the following error message to MtLogTailer.log until the local disk was filled.
```
2015-05-11T13:13:56.4995462Z System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at System.IO.BinaryReader.InternalReadOneChar()
   at System.IO.BinaryReader.Read()
   at MtLogTailer.LogShipper.ReadLine(BinaryReader reader, StringBuilder buf)
   at MtLogTailer.LogShipper.ShipLogData(Stream stream)
   at MtLogTailer.LogShipper.Process()
   at MtLogTailer.PathWatcher.Process()
```

**Comment by mrdavidlaing** [comment]
@fandrei,

I think there are 3 issues here:

1.  Why does the exception happen once?
2.  Why does the exception happen repeatedly without the MtLogTailer.exe crashing?
3.  Why does it write to a local log file?

**Comment by fandrei** [comment]
agreed. wrt 3 - I added it as a precaution, just in case if exceptions aren't reported to the cluster for some reason. However, I didn't expect any exceptions to happen often.
As the first part of solution, I'll limit this file in size.

**Comment by mrdavidlaing** [comment]
> As the first part of solution, I'll limit this file in size.

:+1:

**Comment by fandrei** [comment]
https://github.com/cityindex/LogSearchShipper/pull/101
