### ISSUE TITLE
MT tailer - repetitive exceptions

### ISSUE THREAD

**Issue by fandrei** [cityindex/LogSearchShipper#95]
mrdavidlaing at 13:12
 We seem to have these 2 errors:

```
2015-04-29T00:28:12.0131512Z System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.\r\nParameter name: chars\r\n   at System.Text.Encoding.ThrowCharsOverflow()\r\n   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)\r\n   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)\r\n   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)\r\n   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)\r\n   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)\r\n   at System.IO.BinaryReader.InternalReadOneChar()\r\n   at System.IO.BinaryReader.Read()\r\n   at MtLogTailer.LogShipper.ReadLine(BinaryReader reader, StringBuilder buf)\r\n   at MtLogTailer.LogShipper.ShipLogData(Stream stream)\r\n   at MtLogTailer.LogShipper.Process()\r\n   at MtLogTailer.PathWatcher.Process()
```

```
2015-04-29T00:28:12.6042631Z System.IO.DirectoryNotFoundException: Could not find a part of the path '\\RDB-SRV-MTDEM01\Apps\MetaTrader4Server\logs'.\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileSystemEnumerableIterator`1.CommonInit()\r\n   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)\r\n   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)\r\n   at MtLogTailer.PathWatcher.Process() in c:\Dev\logsearch-shipper.NET\src\MtLogTailer\PathWatcher.cs:line 34
```

repeated over and over around the time the log file was “rolled"

**Comment by fandrei** [comment]
@mrdavidlaing, btw - are thought the MT logs aren't supposed to be rolled?

**Comment by mrdavidlaing** [comment]
@fandrei - MT4 logs aren't rolled; rather a new log is started with a new YYYYMMDD.log filename every day.

However, appears that when MT4 starts a new log file, it trims the NULLs off the end of the old one; which might explain the strange behaviour we see.

When I go look at the end of the current day's log file, I see this:
![screen shot 2015-05-05 at 10 06 42](https://cloud.githubusercontent.com/assets/227505/7469709/8df2a466-f30e-11e4-9389-70214df759ec.png)

When I go look at the end of yesterday's log file, I see this:
![screen shot 2015-05-05 at 10 07 11](https://cloud.githubusercontent.com/assets/227505/7469710/93abae02-f30e-11e4-9e51-9571aac137fa.png)
